### ISSUE TITLE
Consider making `file_key` config variable required

### ISSUE THREAD

**Issue by peytondmurray** [North-West-Wind/cls#2]
Hey, I came across `cls` recently and am really enjoying using it - thanks for the awesome piece of software.

When I first installed `cls==1.2.0` I found that I couldn't assign global keybindings to certain sounds. After a quick look through the code base, it seems like the default configuration has an [optional `file_key`](https://github.com/North-West-Wind/cls/blob/9f286ee07afb16edc0b07f16e5fbcf1796e505af/src/config.rs#L12), so by default that config variable doesn't get written to `~/.config/cls/config.toml`. As a result, new users who try to set global keybindings are unable to do so, with the [critical path silently ignoring](https://github.com/North-West-Wind/cls/blob/9f286ee07afb16edc0b07f16e5fbcf1796e505af/src/component/block/files.rs#L190) me when I press `x` inside the `Files` block because `app.config.file_key` doesn't exist.

It might make sense to make this config variable required (but an empty hashmap) instead, so that new users can start setting keymaps right away. I'm not too familiar with rust, but I'm pretty confident I can figure out how to do this anyway - so let me know if you'd accept a PR for this. Cheers!

**Comment by North-West-Wind** [comment]
I did realize this while updating it today. It's fixed and will be included in the next release (1.3.0) :>  
Thank you for using `cls`!
